In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:2]

['emma', 'olivia']

In [3]:
len(words)

32033

In [4]:
#Build the vocabulary of characters and mapping to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [5]:
# Building The dataset

block_size = 3 # context length : how many characters we take to predict the next one

X, Y = [], []
for w in words[:1]:
    print(w)
    
    # context = [0]
    # print(context)
    
    context = [0] * block_size
    # print(context)

    # x = w + '.'
    
    # print(x)
    
    for ch in w + '.':
        ix = stoi[ch] # 5
        X.append(context)
        # print(X)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '------>', itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)
        

emma
... ------> e
..e ------> m
.em ------> m
emm ------> a
mma ------> .


In [6]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1]])

In [7]:
Y

tensor([ 5, 13, 13,  1,  0])

In [8]:
seed = torch.Generator().manual_seed(123456)

In [9]:
# Embedding Table / Glorified Lookup table
C = torch.randn((27,2), generator=seed)
C

tensor([[-1.1218, -1.8445],
        [ 1.0258,  2.1921],
        [-1.4322,  1.5293],
        [ 1.2118,  0.0423],
        [ 0.3807,  0.0538],
        [ 0.5047, -0.4987],
        [-0.4891,  0.0578],
        [ 0.9436,  0.9775],
        [ 0.7843, -0.1034],
        [ 0.1187, -0.2737],
        [ 1.1537,  1.3910],
        [ 1.0732, -1.2210],
        [ 0.9103,  0.8257],
        [ 0.1247,  0.8079],
        [ 0.1415, -0.5531],
        [ 1.0828, -1.7865],
        [-0.7372, -0.7429],
        [-0.4891,  2.4613],
        [-0.7179, -0.2446],
        [-0.8818,  1.6565],
        [-0.5419, -2.4956],
        [ 0.3731,  1.2806],
        [-0.1539,  0.2954],
        [-1.5935, -0.0451],
        [-0.2014, -0.7450],
        [-0.2250,  0.0894],
        [-1.0029, -1.1601]])

In [10]:
C[5]

tensor([ 0.5047, -0.4987])

In [11]:
emb = C[X]
emb.shape

torch.Size([5, 3, 2])

In [12]:
W1 = torch.randn((6,100))
b1 = torch.randn(100)

In [13]:
emb

tensor([[[-1.1218, -1.8445],
         [-1.1218, -1.8445],
         [-1.1218, -1.8445]],

        [[-1.1218, -1.8445],
         [-1.1218, -1.8445],
         [ 0.5047, -0.4987]],

        [[-1.1218, -1.8445],
         [ 0.5047, -0.4987],
         [ 0.1247,  0.8079]],

        [[ 0.5047, -0.4987],
         [ 0.1247,  0.8079],
         [ 0.1247,  0.8079]],

        [[ 0.1247,  0.8079],
         [ 0.1247,  0.8079],
         [ 1.0258,  2.1921]]])

In [14]:
emb[:,0,:],emb[:,1,:],emb[:,2,:]

(tensor([[-1.1218, -1.8445],
         [-1.1218, -1.8445],
         [-1.1218, -1.8445],
         [ 0.5047, -0.4987],
         [ 0.1247,  0.8079]]),
 tensor([[-1.1218, -1.8445],
         [-1.1218, -1.8445],
         [ 0.5047, -0.4987],
         [ 0.1247,  0.8079],
         [ 0.1247,  0.8079]]),
 tensor([[-1.1218, -1.8445],
         [ 0.5047, -0.4987],
         [ 0.1247,  0.8079],
         [ 0.1247,  0.8079],
         [ 1.0258,  2.1921]]))

In [15]:
torch.concat(torch.unbind(emb,1),1)

tensor([[-1.1218, -1.8445, -1.1218, -1.8445, -1.1218, -1.8445],
        [-1.1218, -1.8445, -1.1218, -1.8445,  0.5047, -0.4987],
        [-1.1218, -1.8445,  0.5047, -0.4987,  0.1247,  0.8079],
        [ 0.5047, -0.4987,  0.1247,  0.8079,  0.1247,  0.8079],
        [ 0.1247,  0.8079,  0.1247,  0.8079,  1.0258,  2.1921]])

In [16]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [17]:
a.shape

torch.Size([18])

In [18]:
a.view(3,3,2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [19]:
a.storage()

/tmp/ipykernel_18318/214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [20]:
emb.storage()

 -1.1218369007110596
 -1.8445433378219604
 -1.1218369007110596
 -1.8445433378219604
 -1.1218369007110596
 -1.8445433378219604
 -1.1218369007110596
 -1.8445433378219604
 -1.1218369007110596
 -1.8445433378219604
 0.504667341709137
 -0.49874359369277954
 -1.1218369007110596
 -1.8445433378219604
 0.504667341709137
 -0.49874359369277954
 0.12470921874046326
 0.8078563213348389
 0.504667341709137
 -0.49874359369277954
 0.12470921874046326
 0.8078563213348389
 0.12470921874046326
 0.8078563213348389
 0.12470921874046326
 0.8078563213348389
 0.12470921874046326
 0.8078563213348389
 1.02579927444458
 2.192124843597412
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 30]

In [21]:
emb.view(5,6)

tensor([[-1.1218, -1.8445, -1.1218, -1.8445, -1.1218, -1.8445],
        [-1.1218, -1.8445, -1.1218, -1.8445,  0.5047, -0.4987],
        [-1.1218, -1.8445,  0.5047, -0.4987,  0.1247,  0.8079],
        [ 0.5047, -0.4987,  0.1247,  0.8079,  0.1247,  0.8079],
        [ 0.1247,  0.8079,  0.1247,  0.8079,  1.0258,  2.1921]])

In [22]:
h = emb.view(-1,6) @ W1 + b1

In [23]:
h

tensor([[ 1.0572e+01, -4.1177e+00, -6.9574e-01,  1.7141e+00,  1.8061e+00,
         -5.5658e-01,  4.2189e+00, -2.2863e+00, -4.9755e+00, -1.3094e+00,
         -1.4168e+01, -5.7204e+00, -1.4358e+00,  6.5745e+00,  4.6153e+00,
         -3.3436e+00, -8.9222e-01, -4.4500e-01,  3.2392e+00,  1.2758e+00,
         -1.1557e+00, -4.1560e-01,  1.4436e+00, -2.1357e+00,  6.7335e+00,
         -4.1136e-01,  5.5189e+00, -1.8919e+00, -5.3094e-01,  5.7612e+00,
          7.5372e-01, -5.7430e+00, -2.5469e+00,  2.4855e+00, -4.8362e+00,
         -3.9700e+00,  1.8004e+00,  4.2339e+00,  1.5259e+00, -6.7578e+00,
         -4.4344e+00,  1.8730e-01,  1.1474e+00, -7.5211e+00,  5.0642e+00,
          7.6576e-01, -5.0980e+00,  1.2786e+00,  1.2590e+00, -2.2356e+00,
          5.6004e+00,  9.1029e-02, -5.8285e+00,  1.2418e+00, -5.6530e-01,
         -1.2647e+00, -5.1086e+00,  6.6838e-01,  1.1537e+00,  2.3121e-01,
          1.5001e+00, -2.4648e+00, -5.6724e+00,  1.6535e+00,  5.8313e+00,
          4.4335e+00, -3.3473e-02,  7.

In [24]:
h = torch.tanh(h)

In [25]:
h.shape

torch.Size([5, 100])

In [26]:
W2 = torch.randn((100,27), generator=seed)
b2 = torch.randn(27, generator=seed)

In [27]:
logits = h @ W2 + b2
logits

tensor([[-1.4835e+01,  3.5550e+00,  4.2066e+00,  5.6885e+00,  6.6665e+00,
          1.9216e+00, -1.1743e+01,  5.9082e+00, -1.1521e-01, -2.6146e+01,
          1.6479e+00, -1.3602e-01,  6.5452e+00,  1.9041e+00, -7.1682e+00,
         -7.2747e-01,  1.0334e+01,  1.3504e+00,  8.6367e+00, -2.9697e+00,
          7.0687e+00,  1.7468e+01, -8.7111e-01, -1.0205e+01,  4.2220e+00,
         -1.0823e+01, -5.6589e+00],
        [-7.9766e+00,  6.2647e+00, -4.2574e+00, -1.3108e+01,  1.4620e+01,
          2.9691e+00, -8.8837e+00,  4.0039e+00, -2.8162e+00, -2.7262e+01,
         -4.7960e+00, -1.6000e-01,  7.5031e+00, -9.1475e+00, -3.5199e+00,
          1.1092e+01,  9.6591e+00,  2.2726e+00, -5.2994e+00, -1.1522e+01,
          3.9078e+00,  1.4938e+01,  2.3026e-01, -6.6934e+00,  2.2397e+00,
         -1.0410e+01, -5.2542e+00],
        [ 2.0613e+00,  1.1682e+01, -5.8195e+00, -1.2460e+01,  1.0226e+01,
         -7.4469e+00, -4.0324e+00,  1.3523e+01,  1.5488e+00, -2.3735e+01,
         -1.4956e+01,  2.8762e+00, -3.91

In [28]:
logits.shape

torch.Size([5, 27])

In [29]:
counts = logits.exp()

In [30]:
probs = counts / counts.sum(1, keepdims=True)
probs

tensor([[9.3433e-15, 9.0615e-07, 1.7386e-06, 7.6517e-06, 2.0348e-05, 1.7694e-07,
         2.0580e-13, 9.5315e-06, 2.3080e-08, 1.1434e-19, 1.3457e-07, 2.2605e-08,
         1.8023e-05, 1.7387e-07, 1.9961e-11, 1.2513e-08, 7.9678e-04, 9.9939e-08,
         1.4593e-04, 1.3291e-09, 3.0420e-05, 9.9897e-01, 1.0838e-08, 9.5750e-13,
         1.7656e-06, 5.1628e-13, 9.0293e-11],
        [6.3675e-11, 9.7478e-05, 2.6256e-09, 3.7636e-13, 4.1446e-01, 3.6113e-06,
         2.5707e-11, 1.0163e-05, 1.1095e-08, 2.6808e-19, 1.5322e-09, 1.5801e-07,
         3.3631e-04, 1.9745e-11, 5.4891e-09, 1.2177e-02, 2.9047e-03, 1.7996e-06,
         9.2613e-10, 1.8378e-12, 9.2325e-06, 5.7000e-01, 2.3345e-07, 2.2977e-10,
         1.7412e-06, 5.5895e-12, 9.6896e-10],
        [5.3749e-10, 8.0999e-06, 2.0311e-13, 2.6525e-16, 1.8886e-06, 3.9900e-14,
         1.2131e-12, 5.1046e-05, 3.2194e-10, 3.3665e-21, 2.1874e-17, 1.2141e-09,
         4.6237e-11, 1.2725e-12, 6.3925e-13, 5.2657e-08, 5.6332e-07, 1.0077e-11,
         7.0001e-

In [31]:
probs.shape

torch.Size([5, 27])

In [32]:
probs[0].sum()

tensor(1.0000)

In [33]:
loss = -probs[torch.arange(5),Y].log().mean()
loss

tensor(16.1535)

In [34]:
# Model

In [35]:
X.shape, Y.shape

(torch.Size([5, 3]), torch.Size([5]))

In [36]:
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((27,2),generator=g, requires_grad=True)
W1 = torch.randn((6,100), generator=g, requires_grad=True)
b1 = torch.randn(100, generator=g, requires_grad=True)
W2 = torch.randn((100,27), generator=g, requires_grad=True)
b2 = torch.randn(27,generator=g, requires_grad=True)
parameters = [C, W1, b1, W2, b2]

In [37]:
sum(p.nelement() for p in parameters)

3481

In [38]:
learning_rate = -0.1

In [52]:
for _ in range(10):
    # Forward Pass
    xemb = C[X] # 5,3,2
    # --- Neuron ----
    h = xemb.view(-1,6) @ W1 + b1
    h = torch.tanh(h)
    
    # --- Loss Calc ----
    logits = h @ W2 + b2
    # counts = logits.exp()
    # probs = counts / counts.sum(1, keepdims=True)
    # loss = -probs[torch.arange(5),Y].log().mean()
    loss = F.cross_entropy(logits,Y)
    print(loss.item())
    
    # Back Prop
    for p in parameters:
        p.grad = None
    loss.backward()
    
    # Update
    for p in parameters:
        p.data += -0.01 * p.grad

7.586902618408203
7.0653181076049805
6.5641350746154785
6.084296703338623
5.625845909118652
5.187582492828369
4.767600059509277
4.364169120788574
3.9764564037323
3.604748487472534


In [40]:
logits.max(1)

torch.return_types.max(
values=tensor([15.3890, 17.2643, 20.9619, 16.6225, 12.2919], grad_fn=<MaxBackward0>),
indices=tensor([ 9, 10,  9, 14,  2]))

# MLP Explained

In [160]:
# === Building a dataset ===
xs = []
ys = []

block_size = 3
content = [0] * 3

for w in words[:1]: 
    for ch in w + '.':
        ix = stoi[ch]
        xs.append(content)
        ys.append(ix)
        content = content[1:] + [ix]

xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [161]:
xs,ys

(tensor([[ 0,  0,  0],
         [ 0,  0,  5],
         [ 0,  5, 13],
         [ 5, 13, 13],
         [13, 13,  1]]),
 tensor([ 5, 13, 13,  1,  0]))

In [162]:
seedz = torch.Generator().manual_seed(2147483647) # For making it deterministic

In [163]:
# === LAYER BUILDING ===
Cz = torch.randn((27,2),generator=seedz, requires_grad=True) # embedding Matrix

In [178]:
# ==== Embedding + Foward Pass ===
xs_embedded = Cz[xs]

In [165]:
# === 1st layer ===
# XS contains a shape of [...,3(context window),2(embedding vectors)]
W1 = torch.randn((6,100), generator=seedz, requires_grad=True) # weights matrix
b1 = torch.randn((100), generator=seedz, requires_grad=True) # bias matrix

In [179]:
# === Defining Neurons in 1st Layer + Forward Pass ===
h = xs_embedded.view(-1,6) @ W1 + b1
h = torch.tanh(h)

In [167]:
# === 2nd Layer ===

W2 = torch.randn((100,27), generator=seedz, requires_grad=True)
b2 = torch.randn((27), generator=seedz, requires_grad=True)

In [168]:
parameters = [Cz, W1, b1, W2, b2]

In [180]:
# === Defining Neurons in 2nd Layer + Forward Pass ===
logits = h @ W2 + b2

In [181]:
# === Loss Calculation
loss = F.cross_entropy(logits, ys)
print(loss.item())

15.248146057128906


In [182]:
# === Backpropagation ===
for p in parameters:
    p.grad = None
    
loss.backward()

In [183]:
# === Updating Data
for p in parameters:
    p.data += -0.1 * p.grad

# GPU Bigram MLP

In [347]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [348]:
block_size = 3
gx = []
gy = []

for w in words:
    content = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        gx.append(content)
        gy.append(ix)
        content = content[1:] + [ix]

In [349]:
gx = torch.tensor(gx).to(device)
gy = torch.tensor(gy).to(device)

In [350]:
gg = torch.Generator(device=device).manual_seed(2147483647)

In [351]:
gC = torch.randn((27,2), generator=g).to(device)
gW1 = torch.randn((6,100), generator=g).to(device)
gb1 = torch.randn((100), generator=g).to(device)
gW2 = torch.randn((100,27), generator=g).to(device)
gb2 = torch.randn((27), generator=g).to(device)
parameters = [gC, gW1, gb1, gW2, gb2]

In [352]:
sum(p.nelement() for p in parameters)

3481

In [353]:
for p in parameters:
    p.requires_grad = True

In [354]:
lre = torch.linspace(-3,0,1000)
lrs = 10**lre

In [382]:
lri = []
lossi = []

for i in range(1000):

    # minibatch construct
    ix = torch.randint(0, gx.shape[0], (32,))
    
    # Forward Pass
    gx_emb = gC[gx[ix]]
    h = torch.tanh(gx_emb.view(-1,6) @ gW1 + gb1)
    logits = h @ gW2 + gb2
    loss = F.cross_entropy(logits,gy[ix])
    #print(loss.item())
    
    # Back Propagation
    for p in parameters:
        p.grad = None
    loss.backward()
    
    # Update
    lr = 0.01
    for p in parameters:
        p.data += -lr * p.grad

    #track stats
    # lri.append(lrs[i])
    # lossi.append(loss.item())
        
#print(loss.item())

In [383]:
gx_emb = gC[gx]
h = torch.tanh(gx_emb.view(-1,6) @ gW1 + gb1)
logits = h @ gW2 + gb2
loss = F.cross_entropy(logits,gy)
print(loss.item())

2.2492356300354004


In [ ]:
# training split, dev/validation split, test split.
# 80% , 10%, 10%